# Numpy


numpy (Numerical Python) is an open source python library that's used in almost every field of science and engineering. its the universal statndard for working with numerical data in python and its at the core of the scientific python and PyData ecosystems.

the numpy lib contain a miltidimensional array and matrix data structure.

In [1]:
import numpy as np

In [2]:
arr = np.array([12,13,14,15,16])
print(arr)
print(type(arr))

[12 13 14 15 16]
<class 'numpy.ndarray'>


In [3]:
tup = np.array((12,13,14,15,16))
print(tup)
print(type(tup))

[12 13 14 15 16]
<class 'numpy.ndarray'>


### Dimension of Array

0-D Array

ndim - find dimension of array

In [4]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


1-D Array

In [5]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1


2-D Array

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


3-D Array

In [7]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


### check number of dimension

In [9]:
a= np.array(10)
b= np.array([1,2,3,4,5])
c= np.array([[1,2,3],[4,5,6]])
d= np.array([[[1,2,3],[4,5,6]],[[9,8,7],[6,5,4]]])


print(f" Dimension of a : {a.ndim}")
print(f" Dimension of b : {b.ndim}")
print(f" Dimension of c : {c.ndim}")
print(f" Dimension of d : {d.ndim}")

 Dimension of a : 0
 Dimension of b : 1
 Dimension of c : 2
 Dimension of d : 3


## NumPy Array Indexing

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[2])

3


Get thied and sixth and 8th element from the following array and add them.

In [11]:
arr = np.array([12,34,24,45,65,72,28,20,49,59,44,45])
print(f"third element {arr[2]}")
print(f"sixth element {arr[5]}")
print(f"8th element {arr[7]}")

print(f"add of 3rd 6th and 8th element {arr[2]+arr[5]+arr[7]}")

third element 24
sixth element 72
8th element 20
add of 3rd 6th and 8th element 116


## 2D array indexing

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

print(f"second element of 1st row { arr[0][1]}")

# or 

print(f"second element of 1st row { arr[0,1]}")

print(f"second element of 2nd row { arr[1][1]}")



second element of 1st row 2
second element of 1st row 2
second element of 2nd row 5


Add the first element of row 1 and last element of row 2.


In [19]:
arr= np.array([[10,20,30,40],[50,60,70,80]])

print(f"first element of 1st row : {arr[0,0]}")
print(f"last element of 2nd row : {arr[1,-1]}")
print(f"And there sum is { arr[0,0]+arr[1,-1]}")

first element of 1st row : 10
last element of 2nd row : 80
And there sum is 90


## 3D array indexing 

In [25]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"first element of arr {arr[0,0,0]}")

print(f"last element of arr {arr[-1,-1,-1]}")

first element of arr 1
last element of arr 12
