In [1]:
import numpy as np

## Slicing of numpy array

1D array slicing

In [3]:
arr= np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])
print(arr[::2])

[2 3 4 5]
[1 3 5 7 9]


2D array slicing

In [4]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0,1:3])

print(arr[1,2:4])

[2 3]
[8 9]


3D array slicing

In [8]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])

print(arr)
print(arr[0,0,0:2])
print(arr[1,2,0:2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
[1 2]
[17 18]


# Data type of NumPy

NumPy has some extra data types , and refer to data types with one character, like --

i -> integer

b -> boolean

u -> unsigned integer

f -> float

c -> complex float

m -> timedelta

M -> deltatime

O -> object

S -> string

U -> unicode string

V -> fixed chunk of memeory for other type (void)

## checking the data type of an array

In [10]:
arr= np.array([1,2,33,45,66])
print(arr.dtype)

int32


In [11]:
arr = np.array(["cow","dog","cat"])
print(arr.dtype)

<U3


## creating arrays with a define data type

In [12]:
arr = np.array([1,23,44,5,6,8], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'23' b'44' b'5' b'6' b'8']
|S2


## create an array with data types 4 bytes integer

In [14]:
arr = np.array([1,2,3,4], dtype='i4') # 4 bytes = 32 bits 
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### Numpy array shape

the shape of an array is the number of elements in dimension

Print the shape of 2d array

In [17]:
arr= np.array([[1,2,3],[4,56,7]])
print(f"shape of array {arr.shape}")

shape of array (2, 3)


In [20]:
arr= np.array([[[1,2,3],[4,56,7]],[[1,2,3],[4,56,7]]])
print(arr)
print(f"shape of array {arr.shape}")

[[[ 1  2  3]
  [ 4 56  7]]

 [[ 1  2  3]
  [ 4 56  7]]]
shape of array (2, 2, 3)


## Joining numpy array

In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


## join 2D array

In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([[11,12,13],[14,15,16]])

print("join row wise")
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)
print("---------------------")
print("join coloum wise")
arr = np.concatenate((arr1,arr2), axis=0)
print(arr)


join row wise
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]
---------------------
join coloum wise
[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


# Spliting numpy array

### spliting the array in 3 & 4 parts

In [27]:
arr= np.array([1,2,3,4,5,6])
new_3_arr = np.array_split(arr,3)
new_4_arr = np.array_split(arr,4)

print("before split")
print(arr)
print("split 3 part")
print(new_3_arr)
print("split 4 part")
print(new_4_arr)

before split
[1 2 3 4 5 6]
split 3 part
[array([1, 2]), array([3, 4]), array([5, 6])]
split 4 part
[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel and flatten

-> convert multidimensional array into 1D array

In [34]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(f"dimension is {arr.ndim}")
print("use revel")
n=arr.ravel()
print(n)
print(f"after revel dimension {n.ndim}")

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3
use revel
[1 2 3 4 5 6 7 8 9]
after revel dimension 1


# Unique function

return_counts - kon si value kitni baar repeated hai

In [37]:
k= np.array([1,2,4,5,2,3,2,1,2,2,24,23,22,3,5,6,7,3,2,3,22])
print(k)

x=np.unique(k)
print(x)

[ 1  2  4  5  2  3  2  1  2  2 24 23 22  3  5  6  7  3  2  3 22]
[ 1  2  3  4  5  6  7 22 23 24]


# delete

In [38]:
arr = np.array([1,2,3,4,5])

d= np.delete(arr,[3])
print(d)

[1 2 3 5]
